export type Phase =
  | "opening" // ページアクセス時のオープニング演出
  | "idle" // カードの山
  | "expanding" // 扇状に広がる
  | "storm" // 激しく舞う(タップは反応演出のみ)
  | "vortex" // 吸い込まれるように中央へ収束
  | "grid" // 整列・選択待ち
  | "selected" // 選択したカードがゆっくり浮き上がる
  | "result"; // 結果表示
